# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

with open("README.md") as f:
    readme = f.read()

setup(
    long_description=readme,
    name="bighead",
    version="0.1.0",
    description="Detects the largest face in an image",
    python_requires=">=3.6",
    author="Chris de Graaf",
    author_email="chrisadegraaf@gmail.com",
    packages=["bighead"],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        "dlib==19.*,>=19.19.0",
        "flask==1.*,>=1.1.1",
        "numpy==1.*,>=1.18.1",
        "requests==2.*,>=2.23.0",
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0",
            "flake8==3.*,>=3.7.9",
            "mypy==0.*,>=0.761.0",
            "pytest-black==0.*,>=0.3.8",
            "pytest-cov==2.*,>=2.8.1",
            "pytest-flake8==1.*,>=1.0.4",
        ]
    },
)
