name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        python:
          - 3.6
          - 3.7
          - 3.8
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: pip install poetry
      - run: poetry install
      - run: poetry run ./test.sh
